2019-12-27 13:43:30,999 ERROR: Exception on /favicon.ico [GET] [ in e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\werkzeug\routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py", line 1815, in handle_user_exception
    return self.handle_http_exception(e)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\app.py", line 1743, in handle_http_exception
    return handler(e)
  File "e:\Users\Caio\Documents\Python\Microblog\app\errors.py", line 6, in not_found_error
    return render_template('404.html'), 404
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "e:\Users\Caio\Documents\Python\Microblog\app\templates\404.html", line 4, in template
    <h1>{{ _(File Not Found) }}</h1>
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 875, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 620, in parse_tuple
    args.append(parse())
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 432, in parse_expression
    return self.parse_condexpr()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 437, in parse_condexpr
    expr1 = self.parse_or()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 547, in parse_unary
    node = self.parse_postfix(node)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 676, in parse_postfix
    node = self.parse_call(node)
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\parser.py", line 767, in parse_call
    self.stream.expect('comma')
  File "e:\Users\Caio\Documents\Python\Microblog\venv\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'Not'
